### ISSUE TITLE
Why do we need 2 vite config

### ISSUE THREAD

**Issue by SiddHyper** [IgnacioNMiranda/vite-component-library-template#74]
Why do we need to vite config one for storybook and one for complete project I have tried using the outside vite config it works like charm so why do we need multiple places vite config apart from this we are using @storybook/react-vite. but there official doc prefers @storybook/builder-vite https://storybook.js.org/docs/react/builders/vite#setup

**Comment by IgnacioNMiranda** [comment]
Hey!
1. You could use the vite.config.ts file that it's in the root of the project for both the lib and the storybook build. I prefer to have them separated as the lib one creates some unnecessary typing files in the `storybook-static` output.

<img width="223" alt="image" src="https://github.com/IgnacioNMiranda/vite-component-library-template/assets/38511917/490b20d8-d18c-4310-a34b-f18c95d02849">

2. I think they can be used interchangeably, and it's just a name alias. In the official [npm package](https://www.npmjs.com/package/@storybook/builder-vite) page they use "@storybook/react-vite" in the example.
<img width="772" alt="image" src="https://github.com/IgnacioNMiranda/vite-component-library-template/assets/38511917/0aa325e9-e8db-4a95-9f87-963cdd07162b">

**Comment by SiddHyper** [comment]
1. Got it thanks for clearing that 
2. Yeah it's just the name I think
