### ISSUE TITLE
I think we should use more eslint plugins

### ISSUE THREAD

**Issue by SiddHyper** [IgnacioNMiranda/vite-component-library-template#75]
As eslint parser we should @typescript-eslint/parser as we are using project with typescript apart from this  we should also use 
eslint-plugin-react-hooks as we react recommend use of hooks

**Comment by IgnacioNMiranda** [comment]
Yeah this makes complete sense! You can add that eslint package to your own implementation of this library. I created this to be a simple template with all the required minimal configuration to make it work and I kept it simple. I don't even use any react hook in the example components haha. If I enhance it in the future with more landed examples, I'll consider to add this package, for sure!
