### ISSUE TITLE
Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by ivansnek** [IgnacioNMiranda/vite-component-library-template#76]
First of all thanks for sharing this cool template @IgnacioNMiranda .

1. I followed and tried to edit it by simple add some dumb counter logic in the existing `AtButton` 

```
export const AtButton = ({ label, variant = 'PRIMARY', isDisabled = false, onClick }: AtButtonProps) => {
  const [counter, setCounter] = useState(0)
  const handleOnClick = (e: any) => {
    setCounter(counter + 1)
    if (! isDisabled && onClick) {
      onClick(e)
    }
  }
  return (
    <button
      className={`transition-colors px-6 py-2 rounded-md ${variantClasses[variant]} ${
        isDisabled ? 'bg-gray-300 text-slate-600 cursor-not-allowed pointer-events-none' : ''
      }`}
      onClick={handleOnClick}
    >
      {label} {counter + 1}
    </button>
  )
}
```
2. Then I ran `pnpm run build:lib`
3. Tested locally by running `npm link` inside the root project
4. In another project I have(stater teamplate of NextJS) I installed by using `npm link vite-component-library-template`

5. Imported the button in the index page using:
```
import {AtButton} from 'vite-component-library-template'
...
<AtButton label="sample" />
```

Then I got this error on runtime: `Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useState')`

![CleanShot 2023-08-11 at 5 24 09](https://github.com/IgnacioNMiranda/vite-component-library-template/assets/1279062/861bfbbb-6783-42ad-b96f-9b5ceb3cdde3)

Hopefully you can give me a hand with this, I had the same issues previously with another lib I was developing and got the same error and I had a sightly different setup(vite.config.js)

**Comment by IgnacioNMiranda** [comment]
Hey! I just tried the exact same, replicating your steps, and it's working on my end. Could you share a repo with the config you're using?

**Comment by ivansnek** [comment]
@IgnacioNMiranda thanks for the quick response, these are my findings:

- I forked your repo here https://github.com/ivansnek/vite-component-library-template, updated with the same code I put above
- I created a sample nextjs project here https://github.com/ivansnek/vite-components-nextjs-test

There are 2 scenarios:

1.Installing the library from npmjs
- I built and published(temporary) the library with the small counter update here https://www.npmjs.com/package/vite-component-library-template-test
- Installing it into the sample [nextjs project](https://github.com/ivansnek/vite-components-nextjs-test)
- This works ok 

2. Installing the library locally
- I deleted the dependency from the installed https://www.npmjs.com/package/vite-component-library-template-test
- Locally on the [project](https://github.com/ivansnek/vite-component-library-template) I ran `pnpm run build` then ` npm link`
- Inside the test NextJS project I ran `npm link vite-component-library-template-test `
- I ran `npm run dev`
- I get the above error

Where you able to test it locally or did you installed your own library from: https://www.npmjs.com/package/vite-component-library-template

**Comment by IgnacioNMiranda** [comment]
I tried both and I have no issues 😕 
In 2.b, did you run `pnpm run build` or `pnpm run build:lib`?

What you can try is something similar to what you did in your "UPDATED" comment, but instead creating a tgz file of the library and installing that in your next project, referencing the file path.

```bash
vite-component-library-template $ pnpm run build:lib
vite-component-library-template $ pnpm pack
# the pack command will create a .tgz with the library bundle. It will also delete the dependencies from your package.json file because of the `prepack` script so remember to readd them.
```

Then in your next project:

```bash
next-app $ npm i ../vite-component-library-template/vite-component-library-template-2.0.3.tgz
```

**Comment by ivansnek** [comment]
@IgnacioNMiranda that las suggestion worked on my side, using the .tgz file locally, thanks so much! 🙏🏼
