### ISSUE TITLE
restore package.json in postpack

### ISSUE THREAD

**Issue by passos** [IgnacioNMiranda/vite-component-library-template#77]
Currently running `npm pack` or `npm publish` will update the `package.json` file in-place and remove the `dependencies  and `devDependencies`. It's very easy to make a mistake and the commit the changes to the repo which will break the dev environment.

We should restore the `package.json` after pack.

**Comment by IgnacioNMiranda** [comment]
Hi! I did a quick research and cannot find any way to do this in a way that convince me. Do you have any suggestion?

**Comment by mderazon** [comment]
Also got tripped by this. Why does `prepack` need to delete dependencies ?
