### ISSUE TITLE
Publishing this to GitHub packages instead.

### ISSUE THREAD

**Issue by alan-automationworks** [IgnacioNMiranda/vite-component-library-template#78]
Would this configuration make it possible to publish the project to GitHub packages instead?

**Comment by IgnacioNMiranda** [comment]
I've added a workflow example in .github/workflows/github-release-please.yml.
I also wrote a [post](https://igna.hashnode.dev/vite-react-typescript-component-library-template-setup-explanation) explaining how to publish to both NPM and Github. Hope it's helpful (: you can also find it in the README
