### ISSUE TITLE
Component Styles Not Applied Upon Import

### ISSUE THREAD

**Issue by md-moijul** [IgnacioNMiranda/vite-component-library-template#83]
## Description
When consuming components from `vite-component-library-template`, I've noticed that the styles associated with these components do not get applied. 

## Steps to Reproduce
1. Clone the repository:

```git clone git@github.com:IgnacioNMiranda/vite-component-library-template.git```

2. Install dependencies and build the library:

```npm install && npm run build:lib```

3. Link the library for local development (or publish and install it in another project):

```npm link```

4. Create a new project and link `vite-component-library-template` to it:

```npm link vite-component-library-template```

5. Use a component from the library:
```javascript
import { AtButton } from 'vite-component-library-template';

export default function App() {
    return (
        <>
            <p>hello world</p>
            <AtButton label="Click" />
        </>
    );
}
```

## Expected Behavior
The Button component (or any other component from the library) should have its styles applied automatically, reflecting the intended design without requiring additional steps.

## Actual Behavior
The components render without any of the styles defined in the component library, resulting in unstyled or default-styled HTML elements.

![image](https://github.com/IgnacioNMiranda/vite-component-library-template/assets/95830824/901009ac-f503-4ca5-a637-e0e481fe99bc)

**Comment by IgnacioNMiranda** [comment]
Hey @md-moijul the components themselves doesn't include the needed css classes. In order to include it, you also need to import the styles.css file in your higher level App component as I described [here](https://igna.hashnode.dev/vite-react-typescript-component-library-template-setup-explanation#heading-using-the-library)

Hope this helps!
