### ISSUE TITLE
Add ES modules (ESM) support

### ISSUE THREAD

**Issue by RabeeAbuBaker** [IgnacioNMiranda/vite-component-library-template#84]
Thank you for this awesome repo!! 

I get this error after Importing `AtButton` into an ESM project (`"type": "module"`)

![image](https://github.com/IgnacioNMiranda/vite-component-library-template/assets/38038348/1be476ae-9f3f-4ffb-8984-376fbe752ab6)

```
import { AtButton } from "vite-component-library-template";
         ^^^^^^^^
SyntaxError: Named export 'AtButton' not found. The requested module 'vite-component-library-template' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vite-component-library-template';
const { AtButton } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by RabeeAbuBaker** [comment]
I was able to fix this by simply adding a default export  to `src/lib/components/atoms/at-button/index.tsx`

`export default AtButton`

**Comment by IgnacioNMiranda** [comment]
Hey! would you mind creating a PR with the change and an explanation? please also check if it creates any issue for other kind of deployments (:
